version: "2"

services:
  mysql:
    image: mysql:5.7
    ports:
      - 4306:3306
    volumes:
      - ./persistance/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASWORD: admin
      MYSQL_DATABASE: giphdb
      MYSQL_ROOT_PASSWORD: root
  web:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./:/opt/data/
    links:
      - mysql:mysql
    depends_on:
      - mysql
