version: "3"

services:
    php: 
        build: .
        working_dir: /var/www
        ports:
            - 8081:80
        volumes:
            - .:/var/www
            - ./apache/apache.conf:/etc/apache2/sites-available/000-default.conf
            - ~/.ssh:/root/.ssh
        links:
            - mysql 
        depends_on:
            - mysql
    mysql:
        image: mysql:5.6
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: giphydb
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./persistance/mysql:/var/lib/mysql
        healthcheck:
            test: mysql --user=root --password=root -e "select 1"
            interval: 3s
            timeout: 10s
            retries: 10
# volumes:
#     my-datavolume:
#         driver: local